baseURL = "https://jpadams.github.io/"
languageCode = "en-us"
title = "Jeremy Adams - Tech Translator"
theme = "PaperMod"

[params]
  author = "Jeremy Adams"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

